// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuAPQVV1Q8T46_5lx-M3BuIOBcQFE2bTw',
    appId: '1:853237163271:web:b34be3dbf63c2a714e11a2',
    messagingSenderId: '853237163271',
    projectId: 'hoaphat-6c6ce',
    authDomain: 'hoaphat-6c6ce.firebaseapp.com',
    storageBucket: 'hoaphat-6c6ce.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjyAdhJX3YzvGwvu6dPd9JfnFkvr3IZhI',
    appId: '1:853237163271:android:3924432aa50ca7714e11a2',
    messagingSenderId: '853237163271',
    projectId: 'hoaphat-6c6ce',
    storageBucket: 'hoaphat-6c6ce.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHYhrJWbxllHQ1EnyONviN85dha0ZxTac',
    appId: '1:853237163271:ios:2fc4729eb222c32b4e11a2',
    messagingSenderId: '853237163271',
    projectId: 'hoaphat-6c6ce',
    storageBucket: 'hoaphat-6c6ce.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHYhrJWbxllHQ1EnyONviN85dha0ZxTac',
    appId: '1:853237163271:ios:2fc4729eb222c32b4e11a2',
    messagingSenderId: '853237163271',
    projectId: 'hoaphat-6c6ce',
    storageBucket: 'hoaphat-6c6ce.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAuAPQVV1Q8T46_5lx-M3BuIOBcQFE2bTw',
    appId: '1:853237163271:web:994cb09fdef0127f4e11a2',
    messagingSenderId: '853237163271',
    projectId: 'hoaphat-6c6ce',
    authDomain: 'hoaphat-6c6ce.firebaseapp.com',
    storageBucket: 'hoaphat-6c6ce.firebasestorage.app',
  );
}
